local module = {}

local InventorySlots = {
    ["1"] = {
        ["Keybind"] = Enum.KeyCode.One,
        ["Tool"] = nil,
        ["UI"] = nil
    },
    ["2"] = {
        ["Keybind"] = Enum.KeyCode.Two,
        ["Tool"] = nil,
        ["UI"] = nil
    },
    ["3"] = {
        ["Keybind"] = Enum.KeyCode.Three,
        ["Tool"] = nil,
        ["UI"] = nil
    },
    ["4"] = {
        ["Keybind"] = Enum.KeyCode.Four,
        ["Tool"] = nil,
        ["UI"] = nil
    },
    ["5"] = {
        ["Keybind"] = Enum.KeyCode.Five,
        ["Tool"] = nil,
        ["UI"] = nil
    },
}



return module