return {
	["Settings Data"] = {
		["Graphical Options"] = {

		},

		["Miscellanous Options"] = {

		},

		["Input Options"] = {
			["Free Look"] = "Enum.KeyCode.LeftAlt",
			["Shoulder Switch"] = "Enum.KeyCode.Q",
			["First Person"] = "Enum.KeyCode.V",
			["Sprint"] = "Enum.KeyCode.LeftShift",
			["Crouch"] = "Enum.KeyCode.C",
		},
	},

	["PlayerData"] = {
		["CMDRLevel"] = 5,
		
		["Unlocked Items"] = {
			["PrinceRifle"] = true,
			["GraceRevolver"] = true,
		},
	},
}