--[[

If you want to set up your own tripwires:
	
	1. Look for the fuse_hook parts in the trap and tripwire object.
	2. Copy the tripwire Beam to either one of the fuse_hook parts.
	3. On the new Beam, find the Shape category and look for Attachment0 and Attachment1.
	4. Set Attachment0 and Attachment1 of the Beam to the 2 attachments in the fuse_hook parts.
	
If done correctly, you should see the barbed wire trail between the tripwire and the trap.
	
--]]