--[[

PUTTING ON ACCESSORIES:
1. copy position of the limb you want to attach to
2. paste into the accessory model's position

If you animate, you can weld the primarypart of the accessory to the body part you want to attach it to


TIPS FOR MAKING YOUR OWN TERRAIN:

Part to Terrain is a good plugin for getting the basic shape, and then doing manual corrections w/ terrain tools
Plugin here: https://create.roblox.com/store/asset/261634767/Part-to-Terrain

Use Rock for diggable terrain, and Basalt for undiggable areas


FOR ANIMATORS OR PEOPLE WHO USE ANIMATING TOOLS TO POSE:

Each soldier has 2 welds for tools: one Motor6D connecting it to their arm, and one regular weld connecting it to their torso.
If you want the tool to move with their arms, you must disable the torso weld.
You also have to disable the Motor6D on their arm if you don't want the tool to move with their arm.

If this does not suit your workflow, feel free to change the welds in a way that you're most comfortable with.


Contact valkyriecraby on discord if there are errors in the public resources that need to be fixed

--]]